backup_server:
  ros__parameters:
    backup_distance: 0.6
    from_frame: robot_base_footprint
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    to_frame: cart # a reference frame for backing up
    tolerance: 0.1 # tolerance in y direction between "from_frame" and "to_frame" for safety purpose
    use_sim_time: false