shelf_detach_server:
  ros__parameters:
    backup_distance: 0.6
    from_frame: robot_base_link
    qos_overrides:
      /clock:
        subscription:
          depth: 1
          durability: volatile
          history: keep_last
          reliability: best_effort
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    to_frame: cart_goal
    use_sim_time: true