shelf_attach_server:
  ros__parameters:
    activate_elevator: true
    attach_velocity: 0.1
    from_frame: robot_base_footprint
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    real_robot: true
    to_frame: temp_cart
    center_shelf: 0.3
    use_sim_time: false