shelf_detection_real_server:
  ros__parameters:
    frame: robot_cart_laser # frame published by the cart
    front_shelf_offset: 0.7 # helper frame in front of the cart
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
      /tf_static:
        publisher:
          depth: 1
          history: keep_last
          reliability: reliable
    use_sim_time: false