shelf_attach_server:
  ros__parameters:
    activate_elevator: false
    attach_velocity: 0.15
    from_frame: robot_front_cover_link
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    real_robot: false
    to_frame: cart
    center_shelf: 0.70
    use_sim_time: true