shelf_attach_server:
  ros__parameters:
    activate_elevator: true
    attach_velocity: 0.03
    from_frame: robot_base_footprint #robot_front_cover_link
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    real_robot: true
    to_frame: temp_cart # temporary frame to orient and align to cart. This frame is wrt. "robot_cart_laser" frame
    cart_frame: cart # static cart frame used for backing up
    cart_offset: 0.50 # cart offset in front of shelf. Used with "temp_cart"
    center_shelf: 0.25
    use_sim_time: false