shelf_attach_server:
  ros__parameters:
    activate_elevator: true
    attach_velocity: 0.2
    from_frame: robot_base_link
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    real_robot: false
    to_frame: cart
    center_shelf: 0.60
    use_sim_time: true