shelf_detach_server:
  ros__parameters:
    detach_velocity: 0.15
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: true