shelf_attach_server:
  ros__parameters:
    activate_elevator: true
    attach_velocity: 0.03
    from_frame: robot_front_cover_link #robot_front_cover_link
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    real_robot: true
    to_frame: temp_cart
    center_shelf: 0.45 # shelf center: 0.25 + front_cover: 0.20 = 0.45
    use_sim_time: false