# this message is used to make rb1_autonomy callable from ROS client
# xml file: to be processed by autonomy server
# bt_status: tree status (handle SUCCESS/FAILURE)
string bt_xml_file
---
bool bt_status