# request front_offset (deg) - the angle different between front_shelf and front of the robot (default = 0)
# result shelf_found
# result shelf_pose in map frame
float32 front_offset
---
geometry_msgs/PoseStamped shelf_pose
bool shelf_found 